print("¡Hola mundo! Soy tu nueva computadora amiga")
print("Me llamo Vader y hablo español como tú")
print("¿Cómo te llamas?")
mi_nombre = input()
print("¡Hola " + mi_nombre + "! Es un placer conocerte")
print("¿Sabías que acabas de programar? ¡Felicidades!")
print("Vamos a jugar. Piensa en un número del 1 al 10")
print("¿Ya lo pensaste? Presiona Enter")
respuesta = input()
print("¡Creo que pensaste en el número 7!")
print("¿Adiviné? (No importa si no, ¡estoy aprendiendo como tú!)")
print("Gracias por programar conmigo, " + mi_nombre)
print("¡Eres increíble! Sigue practicando y serás un gran programador")