site_name: Vader - Lenguaje de Programación Universal
site_description: Documentación oficial de Vader, el primer lenguaje de programación universal y conversacional en español
site_author: Vader Development Team
site_url: https://vader-lang.org

repo_name: LangVader/core
repo_url: https://github.com/LangVader/core
edit_uri: edit/main/docs/

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy

plugins:
  - search:
      lang: es
  - mkdocstrings:
      handlers:
        python:
          paths: [src, transpilers]

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      permalink: true

nav:
  - Inicio: index.md
  - Guía de Inicio:
    - Instalación: getting-started/installation.md
    - Primer Programa: getting-started/first-program.md
    - Conceptos Básicos: getting-started/concepts.md
  - Sintaxis:
    - Sintaxis Básica: syntax/basic.md
    - Variables y Tipos: syntax/variables.md
    - Estructuras de Control: syntax/control-flow.md
    - Funciones: syntax/functions.md
    - Clases: syntax/classes.md
  - Transpiladores:
    - Introducción: transpilers/introduction.md
    - Python: transpilers/python.md
    - JavaScript: transpilers/javascript.md
    - Java: transpilers/java.md
    - C++: transpilers/cpp.md
    - Rust: transpilers/rust.md
    - Go: transpilers/go.md
  - Generadores:
    - Aplicaciones Web: generators/web-apps.md
    - Aplicaciones Flask: generators/flask-apps.md
    - Proyectos Completos: generators/complete-projects.md
  - Ejemplos:
    - Básicos: examples/basic.md
    - Aplicaciones Web: examples/web.md
    - Algoritmos: examples/algorithms.md
  - API Reference:
    - CLI: api/cli.md
    - Transpiladores: api/transpilers.md
    - Generadores: api/generators.md
  - Desarrollo:
    - Contribuir: development/contributing.md
    - Arquitectura: development/architecture.md
    - Testing: development/testing.md
  - Acerca de: about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/LangVader/core
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/vader-lang/
  version:
    provider: mike
