name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel
    
    - name: Build distribution packages
      run: |
        python -m build
    
    - name: Create release assets
      run: |
        # Crear archivo ZIP con el código fuente
        zip -r vader-source-${GITHUB_REF#refs/tags/}.zip . -x "*.git*" "*.pyc" "__pycache__/*" "*.egg-info/*"
        
        # Crear archivo TAR.GZ
        tar -czf vader-source-${GITHUB_REF#refs/tags/}.tar.gz --exclude='.git*' --exclude='*.pyc' --exclude='__pycache__' --exclude='*.egg-info' .
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          vader-source-*.zip
          vader-source-*.tar.gz
        body: |
          ## 🚀 Vader - Lenguaje de Programación Universal
          
          ### ✨ Características Principales
          - **8 Lenguajes Objetivo**: Python, JavaScript, Java, C++, Rust, Go, HTML/CSS, Solidity
          - **Sintaxis Natural**: Programación en español conversacional
          - **Generadores de Aplicaciones**: Web, Flask, proyectos completos
          - **Testing Automático**: Suite completa de pruebas
          - **CI/CD Integrado**: Pipeline automático de calidad
          
          ### 📦 Instalación
          ```bash
          # Desde PyPI (próximamente)
          pip install vader-lang
          
          # Desde código fuente
          git clone https://github.com/tu-usuario/vader.git
          cd vader
          python -m pip install -e .
          ```
          
          ### 🎯 Uso Rápido
          ```bash
          # Transpilar código Vader
          python src/vader.py mi_programa.vdr --target python
          
          # Generar aplicación web
          python src/app_generator.py mi_app.vdr --type web
          
          # Generar proyecto completo
          python src/project_generator.py mi_proyecto.vdr --languages python,javascript
          ```
          
          ### 🧪 Testing
          ```bash
          # Ejecutar todos los tests
          python test_transpilers.py
          python test_new_transpilers.py
          python test_flask_app_generator.py
          ```
          
          ### 📚 Documentación
          - [Guía de Inicio](docs/GETTING_STARTED.md)
          - [Sintaxis Vader](docs/SYNTAX_GUIDE.md)
          - [API Reference](docs/API_REFERENCE.md)
          - [Ejemplos](examples/)
          
          ### 🐛 Reportar Issues
          Si encuentras algún problema, por favor [crea un issue](https://github.com/tu-usuario/vader/issues/new).
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
